# Generated by Django 4.2 on 2024-03-14 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import parler.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='shoptranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aggregator.shop'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['date_created'], name='aggregator__date_cr_ee0d93_idx'),
        ),
        migrations.AddField(
            model_name='promotiontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aggregator.promotion'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='aggregator.shop', verbose_name='Shop'),
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aggregator.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='aggregator.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='aggregator.shop', verbose_name='Shop'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='aggregator.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='price',
            name='promotions',
            field=models.ManyToManyField(to='aggregator.promotion', verbose_name='Promotions'),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aggregator.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='aggregator.category', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='aggregator.shop', verbose_name='Shop'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['-date_updated'], name='aggregator__date_up_5212eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shoptranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='promotiontranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['-date_created'], name='aggregator__date_cr_8afb0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-date_created'], name='aggregator__date_cr_441aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['external_id'], name='aggregator__externa_b15229_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['-date_created'], name='aggregator__date_cr_b72330_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['-date_updated'], name='aggregator__date_up_47d556_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-date_created'], name='aggregator__date_cr_c88485_idx'),
        ),
    ]
