# Generated by Django 4.2 on 2024-03-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alcohol',
        ),
    ]
