# Generated by Django 4.2 on 2024-03-21 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/', verbose_name='Avatar')),
                ('first_name', models.CharField(blank=True, max_length=500, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=500, verbose_name='Last name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('country', models.CharField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('telegram_username', models.CharField(blank=True, max_length=500, verbose_name='Telegram username')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
